typography_spectrum: 0.36625
color:
  brandColors:
    - '#e31f20'
    - '#312e35'
    - '#ffffff'
    - '#c4664a'
    - '#4f6b6f'
  brandStrength: 0.75
  lightness: 0.1875
  saturation: 0
  rhythmicContrast: 0.5
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 1
analytics:
  google: null
  facebook: null
  twitter: null
name: Nuclear Arsenal
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Nuclear Arsenal
description: For Peace & Power
purpose: []
